-- 5-3-transfer-rule — add transfer_pair_id grouping column to public.transactions.
-- Pair-link is a nullable TEXT column ; both rows of a transfer share the same
-- `tp_<base62>` value, generated by the service (apps/api/src/modules/transactions/
-- transactions.service.ts#generateTransferPairId). NOT a foreign key — ADR-0012
-- prefixed-IDs is for models, not grouping columns.
--
-- Hand-written (Supabase pooler hang on `prisma migrate dev` — ADR-0014). Apply
-- via `bun --filter='@pekulo/api' run prisma:migrate:deploy`. Idempotent via
-- Prisma's _prisma_migrations registry + IF NOT EXISTS guards below — safe to
-- re-run by hand if the registry is reset.
--
-- Touched table: public.transactions. RLS policies preserved verbatim (no
-- DROP/CREATE) — db:rls-audit asserts `transactions: 4` post-deploy. AC-10.

BEGIN;

-- ───────────────────────────────────────────────────────────────────────────
-- Step 1 — add the nullable transfer_pair_id column.
-- ───────────────────────────────────────────────────────────────────────────
ALTER TABLE "transactions"
  ADD COLUMN IF NOT EXISTS "transfer_pair_id" TEXT;

-- ───────────────────────────────────────────────────────────────────────────
-- Step 2 — index on (user_id, transfer_pair_id) for the unpair-after-delete
-- path (find sibling by pair). The cardinality is low (most rows are NULL),
-- the index is partial-friendly but Postgres' B-tree handles NULLs natively.
-- ───────────────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS "transactions_user_pair_idx"
  ON "transactions" ("user_id", "transfer_pair_id");

COMMIT;
