"use client";

// apps/web/src/app/(spike)/tamagui-spike/provider.tsx
// The single client boundary for the W2 spike. All Tamagui runtime context
// (theme switching, animation driver, media-query watcher) lives behind this
// wall.
//
// Reference: https://tamagui.dev/docs/guides/next-js — section "App Router".
//
// Theme wiring:
//   - NextThemeProvider learns our custom theme names ("pekulo-light",
//     "pekulo-dark") via the `themes` prop. Without it, NextThemeProvider
//     defaults to ["light", "dark"] and never raises the right data-theme
//     attribute.
//   - `disableInjectCSS` — the Tamagui static CSS is imported in
//     apps/web/src/app/layout.tsx via `../../public/tamagui.generated.css`
//     (generated by `bun x tamagui generate-css` per tamagui.build.ts),
//     so the provider does NOT need to inject runtime <style> tags for
//     tokens/themes. Without this flag, the runtime would re-evaluate
//     atomic CSS on every render and pump it through useServerInsertedHTML,
//     pegging `next-server` at 269% CPU + 5 GB RAM on /tamagui-spike.
//   - `disableRootThemeClass` — matches the official docs example for
//     App Router. The theme class is applied via NextThemeProvider's
//     data-theme attribute on <html>, not by TamaguiProvider's wrapping
//     <View>. With the static CSS pre-loaded, this works first paint.

import type { ReactNode } from "react";
import { NextThemeProvider } from "@tamagui/next-theme";
import { TamaguiProvider } from "tamagui";

import config from "../../../../tamagui.config";

export function PekuloTamaguiProvider({ children }: { children: ReactNode }) {
  return (
    <NextThemeProvider
      skipNextHead
      defaultTheme="pekulo-dark"
      themes={["pekulo-light", "pekulo-dark"]}
    >
      <TamaguiProvider
        config={config}
        defaultTheme="pekulo-dark"
        disableInjectCSS
        disableRootThemeClass
      >
        {children}
      </TamaguiProvider>
    </NextThemeProvider>
  );
}
