import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
// Tamagui static CSS — generated by `bun x tamagui generate-css` per
// tamagui.build.ts (outputCSS: './public/tamagui.generated.css'). Holds the
// theme/token CSS variables (--t0..--t23 = pekulo colors, --c-radius-*,
// --c-size-*, --c-space-*, font stacks, etc.). Without this import the
// Tamagui runtime re-evaluates atomic CSS on every render of any route
// that mounts a TamaguiProvider — measured live with `top` while the
// reviewer was on /tamagui-spike: next-server hit 269% CPU + 5 GB RAM
// because Turbopack had no static CSS to lean on. With the static file
// imported, the runtime only has to inject *new* per-component slices
// (tamagui's `getNewCSS` short-circuits anything already covered).
import "../../public/tamagui.generated.css";
import { Providers } from "@/components/providers";

export const metadata: Metadata = {
  title: {
    default: "Pekulo",
    template: "%s · Pekulo",
  },
  description:
    "Pekulo — pilote ton plan financier : épargne, projection de capital, portefeuille et hypothèses.",
  applicationName: "Pekulo",
  keywords: ["pekulo", "plan financier", "épargne", "projection", "portefeuille", "ETF", "PEA"],
  authors: [{ name: "Pekulo" }],
  openGraph: {
    type: "website",
    locale: "fr_FR",
    siteName: "Pekulo",
    title: "Pekulo",
    description:
      "Pilote ton plan financier : épargne, projection de capital, portefeuille et hypothèses.",
  },
  twitter: {
    card: "summary",
    title: "Pekulo",
    description:
      "Pilote ton plan financier : épargne, projection de capital, portefeuille et hypothèses.",
  },
  robots: { index: false, follow: false },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr" className="antialiased" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                var t = localStorage.getItem('theme');
                if (!t || t === 'system') {
                  t = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
                }
                if (t === 'dark') document.documentElement.classList.add('dark');
              } catch (e) {}
            `,
          }}
        />
        {/* react-grab observe le DOM en continu. En dev, sur les routes qui
            mutent le DOM par injection CSS atomique (Tamagui sans compiler),
            l'observer amplifie la pression CPU. Opt-in via flag explicite —
            par défaut OFF, à activer ponctuellement (NEXT_PUBLIC_REACT_GRAB=1)
            quand on a besoin de l'inspection. */}
        {process.env.NEXT_PUBLIC_REACT_GRAB === "1" && (
          <Script
            src="//unpkg.com/react-grab/dist/index.global.js"
            crossOrigin="anonymous"
            strategy="beforeInteractive"
          />
        )}
      </head>
      <body className="min-h-screen bg-background text-foreground">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
