// apps/web/src/app/manifest.ts
// Next 16 native PWA manifest route (architecture D7, FR-53). Auto-served at
// /manifest.webmanifest and auto-linked into <head> by Next — no metadata.manifest
// entry needed. Icons are static PNGs generated by scripts/generate-pwa-icons.ts
// into /public/icons. theme/background use the TR-strict dark surface (#000000).
import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Pekulo",
    short_name: "Pekulo",
    description: "Pilote ton plan financier : épargne, projection de capital, portefeuille.",
    start_url: "/dashboard",
    display: "standalone",
    background_color: "#000000",
    theme_color: "#000000",
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      {
        src: "/icons/icon-192-maskable.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/icon-512-maskable.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
